apiVersion: v1
kind: ReplicationController
metadata:
    name: myrc
spec:
    replicas: 3
    selector:
        app: mypod
    template:
        metadata:
            name: nginxpod
            label:
                    app:mypod
        spec:
            containers:
                - name: mynginx
                  image: nginx
                  ports:
                    - containerPort: 80
