apiVersion: v1
kind: Service
metadata:
    name: mypod-svc
spec:
    selector: 
        app: 1stpod 
    type: NodePort 
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30080
